services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P ${SA_PASSWORD} -Q "SELECT * FROM INFORMATION_SCHEMA.TABLES" -C -M -v TrustServerCertificates=true || exit 1
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
      